package work.sample.core.networkException.user.auth

class AccessTokenNotSavedException : AuthException {
    constructor() : super()
    constructor(message: String?) : super(message)
    constructor(message: String?, cause: Throwable?) : super(message, cause)
    constructor(cause: Throwable?) : super(cause)
}